{
 "title": "ATI Delta Build detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "run_id",
    "label": "Run ID",
    "query": "7af10f47-8402-458d-9da5-c64d86abb93d"
   }
  ]
 },
 "panels": [
  {
   "title": "Pass Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT pass_rate FROM build_summaries WHERE run_id = '$run_id'\r\n"
    }
   ]
  },
  {
   "title": "Execution time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT execution_time FROM build_summaries WHERE run_id = '$run_id'\r\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT total FROM build_summaries WHERE run_id = '$run_id'\r\n"
    }
   ]
  },
  {
   "title": "Test composition",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT passed, failed, skipped, unstable\r\nFROM build_summaries WHERE run_id = '$run_id'"
    }
   ]
  },
  {
   "title": "Passed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT passed FROM build_summaries WHERE run_id = '$run_id'\r\n"
    }
   ]
  },
  {
   "title": "Unstable ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT unstable FROM build_summaries WHERE run_id = '$run_id'\r\n"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT failed FROM build_summaries WHERE run_id = '$run_id'\r\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT build_number, branch, author, run_type, build_url, time\r\nFROM build_summaries WHERE run_id = '$run_id'"
    }
   ]
  },
  {
   "title": "XML suite summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT summary_id, type, total, passed, failed, skipped,\r\n       unstable, pass_rate, execution_time, time\r\nFROM xml_test_summaries WHERE run_id = '$run_id'"
    }
   ]
  },
  {
   "title": "Perfomance test summary",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT summary_id, total_requests, rps, mean_latency_ms,\r\n       error_rate, execution_time_s, time\r\nFROM performance_summaries WHERE run_id = '$run_id'"
    }
   ]
  }
 ]
}