{
 "title": "ATI Delta Performance detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "summary_id",
    "query": "a02bb853-b76c-4807-8d9d-b9afc0b56edb"
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT total_requests FROM performance_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "RPS ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT rps FROM performance_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Mean latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT mean_latency_ms FROM performance_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT error_rate FROM performance_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Error Count Composition",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT error_count, (total_requests - error_count) as success_count\r\nFROM performance_summaries WHERE summary_id = '$summary_id'"
    }
   ]
  },
  {
   "title": "Users ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT users FROM performance_summaries WHERE summary_id = '$summary_id'\r\n\r\n"
    }
   ]
  },
  {
   "title": "Spawn rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "users/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT spawn_rate FROM performance_summaries WHERE summary_id = '$summary_id'\r\n\r\n"
    }
   ]
  },
  {
   "title": "Execution time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT execution_time_s FROM performance_summaries WHERE summary_id = '$summary_id'\r\n\r\n"
    }
   ]
  },
  { "title": "Metrics table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT request_method, name, request_count, failure_count,\r\n       median_response_time, average_response_time,\r\n       min_response_time, max_response_time,\r\n       requests_per_s, failures_per_s\r\nFROM performance_metrics\r\nWHERE summary_id = '$summary_id' and name != 'Aggregated'\r\nORDER BY average_response_time DESC"
    }
   ]
  },
  { "title": "Percentile breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT name, p50, p75, p90, p95, p99, p99_90, p99_99, p100\r\nFROM performance_metrics\r\nWHERE summary_id = '$summary_id' and name != 'Aggregated'\r\nORDER BY p99_99 DESC\r\nLIMIT 10"
    }
   ]
  },
  { "title": "Failures table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT method, name, error, occurrences, first_seen, last_seen\r\nFROM performance_failures\r\nWHERE summary_id = '$summary_id'\r\nORDER BY occurrences DESC"
    }
   ]
  }
 ]
}