{
 "title": "ATI Delta XML suite detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "summary_id",
    "query": "083b371d-d82d-4331-a5e7-4af5aec7e1af"
   }
  ]
 },
 "panels": [
  {
   "title": "Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT type FROM xml_test_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Pass rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT pass_rate FROM xml_test_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Execution time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT execution_time FROM xml_test_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Mean test execution",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT mean_test_duration FROM xml_test_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Test composition",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT passed, failed, unstable\r\nFROM xml_test_summaries WHERE summary_id = '$summary_id'"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT total FROM xml_test_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Passed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT passed FROM xml_test_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT failed FROM xml_test_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Unstable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT unstable FROM xml_test_summaries WHERE summary_id = '$summary_id'\r\n"
    }
   ]
  },
  {
   "title": "Failed test list",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT test_id, suite, test_name, status, exec_time\r\nFROM failed_tests\r\nWHERE summary_id = '$summary_id'\r\nORDER BY exec_time DESC"
    }
   ]
  }
 ]
}